// =============================================================================
// 📖 DICCIONARIO DE ITEMS (Español) - EDICIÓN SURVIVAL COMPLETA
// =============================================================================

export const DICCIONARIO_ITEMS = {
    // --- ⚔️ NUEVO 1.21 & COMBATE AVANZADO ---
    "minecraft:mace": "Mazo",
    "minecraft:wind_charge": "Carga de Viento",
    "minecraft:breeze_rod": "Vara de Brisa",
    "minecraft:heavy_core": "Núcleo Pesado",
    "minecraft:trial_key": "Llave de Desafío",
    "minecraft:ominous_trial_key": "Llave de Desafío Ominosa",
    "minecraft:ominous_bottle": "Botella Ominosa",
    "minecraft:wolf_armor": "Armadura de Lobo",
    "minecraft:trident": "Tridente",
    "minecraft:shield": "Escudo",
    "minecraft:totem_of_undying": "Tótem de Inmortalidad",
    "minecraft:elytra": "Élitros",
    "minecraft:spyglass": "Catalejo",
    "minecraft:crossbow": "Ballesta",
    "minecraft:bow": "Arco",
    "minecraft:arrow": "Flecha",
    "minecraft:spectral_arrow": "Flecha Espectral",
    "minecraft:netherite_upgrade_smithing_template": "Plantilla de Mejora de Netherite",

    // --- 💎 MINERALES Y VALIOSOS ---
    "minecraft:diamond": "Diamante",
    "minecraft:netherite_ingot": "Lingote de Netherite",
    "minecraft:netherite_scrap": "Fragmento de Netherite",
    "minecraft:emerald": "Esmeralda",
    "minecraft:gold_ingot": "Lingote de Oro",
    "minecraft:iron_ingot": "Lingote de Hierro",
    "minecraft:copper_ingot": "Lingote de Cobre",
    "minecraft:lapis_lazuli": "Lapislázuli",
    "minecraft:redstone": "Polvo de Redstone",
    "minecraft:quartz": "Cuarzo del Nether",
    "minecraft:amethyst_shard": "Fragmento de Amatista",
    "minecraft:echo_shard": "Fragmento de Eco",
    "minecraft:coal": "Carbón",
    "minecraft:charcoal": "Carbón Vegetal",
    "minecraft:raw_iron": "Hierro Bruto",
    "minecraft:raw_gold": "Oro Bruto",
    "minecraft:raw_copper": "Cobre Bruto",
    "minecraft:gold_nugget": "Pepita de Oro",
    "minecraft:iron_nugget": "Pepita de Hierro",

    // --- 🛠️ HERRAMIENTAS Y ARMADURAS (Sets Completos) ---
    // Netherite
    "minecraft:netherite_sword": "Espada de Netherite",
    "minecraft:netherite_pickaxe": "Pico de Netherite",
    "minecraft:netherite_axe": "Hacha de Netherite",
    "minecraft:netherite_shovel": "Pala de Netherite",
    "minecraft:netherite_hoe": "Azada de Netherite",
    "minecraft:netherite_helmet": "Casco de Netherite",
    "minecraft:netherite_chestplate": "Pechera de Netherite",
    "minecraft:netherite_leggings": "Pantalones de Netherite",
    "minecraft:netherite_boots": "Botas de Netherite",
    // Diamante
    "minecraft:diamond_sword": "Espada de Diamante",
    "minecraft:diamond_pickaxe": "Pico de Diamante",
    "minecraft:diamond_axe": "Hacha de Diamante",
    "minecraft:diamond_shovel": "Pala de Diamante",
    "minecraft:diamond_hoe": "Azada de Diamante",
    "minecraft:diamond_helmet": "Casco de Diamante",
    "minecraft:diamond_chestplate": "Pechera de Diamante",
    "minecraft:diamond_leggings": "Pantalones de Diamante",
    "minecraft:diamond_boots": "Botas de Diamante",
    // Hierro
    "minecraft:iron_sword": "Espada de Hierro",
    "minecraft:iron_pickaxe": "Pico de Hierro",
    "minecraft:iron_axe": "Hacha de Hierro",
    "minecraft:iron_shovel": "Pala de Hierro",
    "minecraft:iron_hoe": "Azada de Hierro",
    "minecraft:iron_helmet": "Casco de Hierro",
    "minecraft:iron_chestplate": "Pechera de Hierro",
    "minecraft:iron_leggings": "Pantalones de Hierro",
    "minecraft:iron_boots": "Botas de Hierro",
    // Oro
    "minecraft:golden_sword": "Espada de Oro",
    "minecraft:golden_pickaxe": "Pico de Oro",
    "minecraft:golden_axe": "Hacha de Oro",
    "minecraft:golden_shovel": "Pala de Oro",
    "minecraft:golden_hoe": "Azada de Oro",
    "minecraft:golden_helmet": "Casco de Oro",
    "minecraft:golden_chestplate": "Pechera de Oro",
    "minecraft:golden_leggings": "Pantalones de Oro",
    "minecraft:golden_boots": "Botas de Oro",
    // Piedra y Madera
    "minecraft:stone_sword": "Espada de Piedra",
    "minecraft:stone_pickaxe": "Pico de Piedra",
    "minecraft:stone_axe": "Hacha de Piedra",
    "minecraft:stone_shovel": "Pala de Piedra",
    "minecraft:stone_hoe": "Azada de Piedra",
    "minecraft:wooden_sword": "Espada de Madera",
    "minecraft:wooden_pickaxe": "Pico de Madera",
    "minecraft:wooden_axe": "Hacha de Madera",
    "minecraft:wooden_shovel": "Pala de Madera",
    "minecraft:wooden_hoe": "Azada de Madera",
    // Varios 
    "minecraft:flint_and_steel": "Mechero",
    "minecraft:shears": "Tijeras",
    "minecraft:fishing_rod": "Caña de Pescar",
    "minecraft:carrot_on_a_stick": "Caña con Zanahoria",
    "minecraft:warped_fungus_on_a_stick": "Caña con Hongo Distorsionado",
    "minecraft:lead": "Rienda",
    "minecraft:name_tag": "Etiqueta",
    "minecraft:saddle": "Montura",
    "minecraft:brush": "Pincel",
    "minecraft:turtle_helmet": "Caparazón de Tortuga",

    // --- 🍔 COMIDA ---
    "minecraft:enchanted_golden_apple": "Manzana de Notch",
    "minecraft:golden_apple": "Manzana Dorada",
    "minecraft:apple": "Manzana",
    "minecraft:golden_carrot": "Zanahoria Dorada",
    "minecraft:bread": "Pan",
    "minecraft:cooked_beef": "Filete Cocinado",
    "minecraft:beef": "Filete Crudo",
    "minecraft:cooked_porkchop": "Chuleta Cocinada",
    "minecraft:porkchop": "Chuleta Cruda",
    "minecraft:cooked_mutton": "Cordero Cocinado",
    "minecraft:mutton": "Cordero Crudo",
    "minecraft:cooked_chicken": "Pollo Cocinado",
    "minecraft:chicken": "Pollo Crudo",
    "minecraft:cooked_rabbit": "Conejo Cocinado",
    "minecraft:rabbit": "Conejo Crudo",
    "minecraft:cooked_cod": "Bacalao Cocinado",
    "minecraft:cod": "Bacalao Crudo",
    "minecraft:cooked_salmon": "Salmón Cocinado",
    "minecraft:salmon": "Salmón Crudo",
    "minecraft:cake": "Pastel",
    "minecraft:cookie": "Galleta",
    "minecraft:pumpkin_pie": "Pastel de Calabaza",
    "minecraft:mushroom_stew": "Estofado de Champiñones",
    "minecraft:beetroot_soup": "Sopa de Remolacha",
    "minecraft:rabbit_stew": "Estofado de Conejo",
    "minecraft:suspicious_stew": "Estofado Sospechoso",
    "minecraft:honey_bottle": "Frasco de Miel",
    "minecraft:sweet_berries": "Bayas Dulces",
    "minecraft:glow_berries": "Bayas Resplandecientes",
    "minecraft:melon_slice": "Rebanada de Sandía",
    "minecraft:chorus_fruit": "Fruta Coral",
    "minecraft:dried_kelp": "Alga Seca",
    "minecraft:potato": "Patata",
    "minecraft:baked_potato": "Patata Cocida",
    "minecraft:poisonous_potato": "Patata Venenosa",
    "minecraft:carrot": "Zanahoria",
    "minecraft:beetroot": "Remolacha",

    // --- 🔌 REDSTONE Y MECANISMOS ---
    "minecraft:tnt": "Dinamita",
    "minecraft:crafter": "Fabricador (Crafter)",
    "minecraft:piston": "Pistón",
    "minecraft:sticky_piston": "Pistón Pegajoso",
    "minecraft:observer": "Observador",
    "minecraft:dispenser": "Dispensador",
    "minecraft:dropper": "Soltador",
    "minecraft:hopper": "Tolva",
    "minecraft:comparator": "Comparador",
    "minecraft:repeater": "Repetidor",
    "minecraft:lever": "Palanca",
    "minecraft:lightning_rod": "Pararrayos",
    "minecraft:daylight_detector": "Sensor de Luz",
    "minecraft:sculk_sensor": "Sensor de Sculk",
    "minecraft:calibrated_sculk_sensor": "Sensor Calibrado",
    "minecraft:tripwire_hook": "Gancho de Cuerda",
    "minecraft:target": "Diana",
    "minecraft:redstone_lamp": "Lámpara de Redstone",
    "minecraft:copper_bulb": "Bombilla de Cobre",
    "minecraft:note_block": "Bloque Musical",
    "minecraft:slime": "Bloque de Slime",
    "minecraft:honey_block": "Bloque de Miel",
    "minecraft:rail": "Raíl",
    "minecraft:powered_rail": "Raíl Propulsor",
    "minecraft:detector_rail": "Raíl Detector",
    "minecraft:activator_rail": "Raíl Activador",
    "minecraft:minecart": "Vagoneta",
    "minecraft:chest_minecart": "Vagoneta con Cofre",
    "minecraft:hopper_minecart": "Vagoneta con Tolva",
    "minecraft:tnt_minecart": "Vagoneta con TNT",

    // --- 🧱 BLOQUES DE CONSTRUCCIÓN PRINCIPALES ---
    "minecraft:stone": "Piedra",
    "minecraft:cobblestone": "Adoquín",
    "minecraft:mossy_cobblestone": "Adoquín Musgoso",
    "minecraft:smooth_stone": "Piedra Lisa",
    "minecraft:deepslate": "Pizarra Profunda",
    "minecraft:cobbled_deepslate": "Pizarra Adoquinada",
    "minecraft:tuff": "Toba",
    "minecraft:calcite": "Calcita",
    "minecraft:dripstone_block": "Bloque de Espeleotema",
    "minecraft:granite": "Granito",
    "minecraft:diorite": "Diorita",
    "minecraft:andesite": "Andesita",
    "minecraft:obsidian": "Obsidiana",
    "minecraft:crying_obsidian": "Obsidiana Llorosa",
    "minecraft:dirt": "Tierra",
    "minecraft:grass_block": "Bloque de Pasto",
    "minecraft:podzol": "Podzol",
    "minecraft:mycelium": "Micelio",
    "minecraft:clay": "Arcilla",
    "minecraft:sand": "Arena",
    "minecraft:red_sand": "Arena Roja",
    "minecraft:gravel": "Grava",
    "minecraft:glass": "Cristal",
    "minecraft:tinted_glass": "Cristal Opaco",
    "minecraft:bricks": "Ladrillos",
    "minecraft:stone_bricks": "Ladrillos de Piedra",
    "minecraft:nether_bricks": "Ladrillos del Nether",
    "minecraft:quartz_block": "Bloque de Cuarzo",
    "minecraft:prismarine": "Prismarina",
    "minecraft:sea_lantern": "Linterna Marina",
    "minecraft:sponge": "Esponja",
    "minecraft:magma": "Bloque de Magma",
    "minecraft:soul_sand": "Arena de Almas",
    "minecraft:soul_soil": "Tierra de Almas",
    "minecraft:glowstone": "Piedra Luminosa",
    "minecraft:shroomlight": "Hongo Brillante",
    "minecraft:bookshelf": "Librería",
    "minecraft:chiseled_bookshelf": "Librería Cincelada",
    "minecraft:chest": "Cofre",
    "minecraft:ender_chest": "Cofre de Ender",
    "minecraft:barrel": "Barril",
    "minecraft:shulker_box": "Caja de Shulker",
    "minecraft:iron_bars": "Barrotes de Hierro",
    "minecraft:ladder": "Escalera de Mano",
    "minecraft:scaffolding": "Andamio",
    "minecraft:beacon": "Faro Mágico",
    "minecraft:conduit": "Canalizador",
    "minecraft:end_rod": "Vara del End",
    "minecraft:anvil": "Yunque",
    "minecraft:enchanting_table": "Mesa de Encantamientos",
    "minecraft:crafting_table": "Mesa de Trabajo",
    "minecraft:furnace": "Horno",
    "minecraft:blast_furnace": "Alto Horno",
    "minecraft:smoker": "Ahumador",
    "minecraft:loom": "Telar",
    "minecraft:cartography_table": "Mesa de Cartografía",
    "minecraft:grindstone": "Afiladora",
    "minecraft:smithing_table": "Mesa de Herrería",
    "minecraft:stonecutter": "Cortapiedras",
    "minecraft:brewing_stand": "Soporte de Pociones",
    "minecraft:cauldron": "Caldero",
    "minecraft:bell": "Campana",
    "minecraft:jukebox": "Tocadiscos",
    "minecraft:campfire": "Hoguera",
    "minecraft:soul_campfire": "Hoguera de Almas",
    "minecraft:lantern": "Farol",
    "minecraft:soul_lantern": "Farol de Almas",

    // --- 🪵 MADERAS (Troncos Principales) ---
    "minecraft:oak_log": "Tronco de Roble",
    "minecraft:spruce_log": "Tronco de Abeto",
    "minecraft:birch_log": "Tronco de Abedul",
    "minecraft:jungle_log": "Tronco de Jungla",
    "minecraft:acacia_log": "Tronco de Acacia",
    "minecraft:dark_oak_log": "Tronco de Roble Oscuro",
    "minecraft:mangrove_log": "Tronco de Manglar",
    "minecraft:cherry_log": "Tronco de Cerezo",
    "minecraft:crimson_stem": "Tallo Carmesí",
    "minecraft:warped_stem": "Tallo Distorsionado",
    "minecraft:bamboo_block": "Bloque de Bambú",
    "minecraft:stick": "Palo",

    // --- 🌱 NATURALEZA Y DROPS ---
    "minecraft:bone": "Hueso",
    "minecraft:bone_meal": "Polvo de Hueso",
    "minecraft:rotten_flesh": "Carne Podrida",
    "minecraft:string": "Hilo",
    "minecraft:spider_eye": "Ojo de Araña",
    "minecraft:fermented_spider_eye": "Ojo Fermentado",
    "minecraft:gunpowder": "Pólvora",
    "minecraft:ender_pearl": "Perla de Ender",
    "minecraft:ender_eye": "Ojo de Ender",
    "minecraft:blaze_rod": "Vara de Blaze",
    "minecraft:blaze_powder": "Polvo de Blaze",
    "minecraft:magma_cream": "Crema de Magma",
    "minecraft:ghast_tear": "Lágrima de Ghast",
    "minecraft:slime_ball": "Bola de Slime",
    "minecraft:leather": "Cuero",
    "minecraft:rabbit_hide": "Piel de Conejo",
    "minecraft:phantom_membrane": "Membrana de Fantasma",
    "minecraft:ink_sac": "Saco de Tinta",
    "minecraft:glow_ink_sac": "Saco de Tinta Brillante",
    "minecraft:shulker_shell": "Caparazón de Shulker",
    "minecraft:nautilus_shell": "Caparazón de Nautilo",
    "minecraft:heart_of_the_sea": "Corazón del Mar",
    "minecraft:nether_star": "Estrella del Nether",
    "minecraft:dragon_breath": "Aliento de Dragón",
    "minecraft:scute": "Escama de Tortuga",
    "minecraft:armadillo_scute": "Escama de Armadillo",
    "minecraft:feather": "Pluma",
    "minecraft:flint": "Pedernal",
    "minecraft:wheat": "Trigo",
    "minecraft:wheat_seeds": "Semillas de Trigo",
    "minecraft:pumpkin_seeds": "Semillas de Calabaza",
    "minecraft:melon_seeds": "Semillas de Sandía",
    "minecraft:beetroot_seeds": "Semillas de Remolacha",
    "minecraft:bamboo": "Bambú",
    "minecraft:sugar_cane": "Caña de Azúcar",
    "minecraft:cactus": "Cactus",
    "minecraft:kelp": "Alga",
    "minecraft:paper": "Papel",
    "minecraft:book": "Libro",
    "minecraft:writable_book": "Libro y Pluma",
    "minecraft:snowball": "Bola de Nieve",
    "minecraft:egg": "Huevo",

    // --- 🪣 CUBOS Y VARIOS ---
    "minecraft:bucket": "Cubo Vacío",
    "minecraft:water_bucket": "Cubo de Agua",
    "minecraft:lava_bucket": "Cubo de Lava",
    "minecraft:milk_bucket": "Cubo de Leche",
    "minecraft:powder_snow_bucket": "Cubo de Nieve en Polvo",
    "minecraft:axolotl_bucket": "Cubo con Ajolote",
    "minecraft:tadpole_bucket": "Cubo con Renacuajo",
    "minecraft:tropical_fish_bucket": "Cubo con Pez Tropical",
    "minecraft:cod_bucket": "Cubo con Bacalao",
    "minecraft:salmon_bucket": "Cubo con Salmón",
    "minecraft:pufferfish_bucket": "Cubo con Pez Globo",
    "minecraft:armor_stand": "Soporte de Armadura",
    "minecraft:painting": "Cuadro",
    "minecraft:item_frame": "Marco",
    "minecraft:glow_item_frame": "Marco Brillante",
    "minecraft:flower_pot": "Maceta",
    "minecraft:bed": "Cama",

    // --- 🎨 TINTES ---
    "minecraft:white_dye": "Tinte Blanco",
    "minecraft:orange_dye": "Tinte Naranja",
    "minecraft:magenta_dye": "Tinte Magenta",
    "minecraft:light_blue_dye": "Tinte Azul Claro",
    "minecraft:yellow_dye": "Tinte Amarillo",
    "minecraft:lime_dye": "Tinte Lima",
    "minecraft:pink_dye": "Tinte Rosa",
    "minecraft:gray_dye": "Tinte Gris",
    "minecraft:light_gray_dye": "Tinte Gris Claro",
    "minecraft:cyan_dye": "Tinte Cian",
    "minecraft:purple_dye": "Tinte Morado",
    "minecraft:blue_dye": "Tinte Azul",
    "minecraft:brown_dye": "Tinte Marrón",
    "minecraft:green_dye": "Tinte Verde",
    "minecraft:red_dye": "Tinte Rojo",
    "minecraft:black_dye": "Tinte Negro",

    // --- 🛏️ CAMAS (Colores) ---
    "minecraft:white_bed": "Cama Blanca",
    "minecraft:orange_bed": "Cama Naranja",
    "minecraft:magenta_bed": "Cama Magenta",
    "minecraft:light_blue_bed": "Cama Azul Claro",
    "minecraft:yellow_bed": "Cama Amarilla",
    "minecraft:lime_bed": "Cama Lima",
    "minecraft:pink_bed": "Cama Rosa",
    "minecraft:gray_bed": "Cama Gris",
    "minecraft:light_gray_bed": "Cama Gris Claro",
    "minecraft:cyan_bed": "Cama Cian",
    "minecraft:purple_bed": "Cama Morada",
    "minecraft:blue_bed": "Cama Azul",
    "minecraft:brown_bed": "Cama Marrón",
    "minecraft:green_bed": "Cama Verde",
    "minecraft:red_bed": "Cama Roja",
    "minecraft:black_bed": "Cama Negra",

    // --- 🧶 LANAS ---
    "minecraft:white_wool": "Lana Blanca",
    "minecraft:orange_wool": "Lana Naranja",
    "minecraft:magenta_wool": "Lana Magenta",
    "minecraft:light_blue_wool": "Lana Azul Claro",
    "minecraft:yellow_wool": "Lana Amarilla",
    "minecraft:lime_wool": "Lana Lima",
    "minecraft:pink_wool": "Lana Rosa",
    "minecraft:gray_wool": "Lana Gris",
    "minecraft:light_gray_wool": "Lana Gris Claro",
    "minecraft:cyan_wool": "Lana Cian",
    "minecraft:purple_wool": "Lana Morada",
    "minecraft:blue_wool": "Lana Azul",
    "minecraft:brown_wool": "Lana Marrón",
    "minecraft:green_wool": "Lana Verde",
    "minecraft:red_wool": "Lana Roja",
    "minecraft:black_wool": "Lana Negra",

    // --- 🌻 FLORES ---
    "minecraft:dandelion": "Diente de León",
    "minecraft:poppy": "Amapola",
    "minecraft:blue_orchid": "Orquídea Azul",
    "minecraft:allium": "Allium",
    "minecraft:azure_bluet": "Aciano",
    "minecraft:red_tulip": "Tulipán Rojo",
    "minecraft:orange_tulip": "Tulipán Naranja",
    "minecraft:white_tulip": "Tulipán Blanco",
    "minecraft:pink_tulip": "Tulipán Rosa",
    "minecraft:oxeye_daisy": "Margarita",
    "minecraft:cornflower": "Aciano",
    "minecraft:lily_of_the_valley": "Lirio del Valle",
    "minecraft:wither_rose": "Rosa de Wither",
    "minecraft:sunflower": "Girasol",
    "minecraft:lilac": "Lila",
    "minecraft:rose_bush": "Rosal",
    "minecraft:peony": "Peonía",
    "minecraft:pitcher_plant": "Planta Jarra",
    "minecraft:torchflower": "Flor Antorcha",
    "minecraft:spore_blossom": "Flor de Esporas",
    "minecraft:flowering_azalea": "Azalea en Flor",
    "minecraft:azalea": "Azalea",
    "minecraft:moss_block": "Bloque de Musgo",
    "minecraft:moss_carpet": "Alfombra de Musgo",
    "minecraft:big_dripleaf": "Hoja de Goteo Grande",
    "minecraft:small_dripleaf": "Hoja de Goteo Pequeña",
    "minecraft:vine": "Enredadera",
    "minecraft:glow_lichen": "Liquen Brillante",
    "minecraft:lily_pad": "Nenúfar",
    "minecraft:cactus": "Cactus",
    "minecraft:deadbush": "Arbusto Muerto",

    // --- 🚪 PUERTAS Y VALLAS ---
    // Puertas
    "minecraft:oak_door": "Puerta de Roble",
    "minecraft:spruce_door": "Puerta de Abeto",
    "minecraft:birch_door": "Puerta de Abedul",
    "minecraft:jungle_door": "Puerta de Jungla",
    "minecraft:acacia_door": "Puerta de Acacia",
    "minecraft:dark_oak_door": "Puerta de Roble Oscuro",
    "minecraft:mangrove_door": "Puerta de Manglar",
    "minecraft:cherry_door": "Puerta de Cerezo",
    "minecraft:bamboo_door": "Puerta de Bambú",
    "minecraft:crimson_door": "Puerta Carmesí",
    "minecraft:warped_door": "Puerta Distorsionada",
    "minecraft:iron_door": "Puerta de Hierro",
    "minecraft:copper_door": "Puerta de Cobre",
    // Trampillas
    "minecraft:oak_trapdoor": "Trampilla de Roble",
    "minecraft:spruce_trapdoor": "Trampilla de Abeto",
    "minecraft:birch_trapdoor": "Trampilla de Abedul",
    "minecraft:jungle_trapdoor": "Trampilla de Jungla",
    "minecraft:acacia_trapdoor": "Trampilla de Acacia",
    "minecraft:dark_oak_trapdoor": "Trampilla de Roble Oscuro",
    "minecraft:mangrove_trapdoor": "Trampilla de Manglar",
    "minecraft:cherry_trapdoor": "Trampilla de Cerezo",
    "minecraft:bamboo_trapdoor": "Trampilla de Bambú",
    "minecraft:crimson_trapdoor": "Trampilla Carmesí",
    "minecraft:warped_trapdoor": "Trampilla Distorsionada",
    "minecraft:iron_trapdoor": "Trampilla de Hierro",
    "minecraft:copper_trapdoor": "Trampilla de Cobre",
    // Vallas
    "minecraft:oak_fence": "Valla de Roble",
    "minecraft:spruce_fence": "Valla de Abeto",
    "minecraft:birch_fence": "Valla de Abedul",
    "minecraft:jungle_fence": "Valla de Jungla",
    "minecraft:acacia_fence": "Valla de Acacia",
    "minecraft:dark_oak_fence": "Valla de Roble Oscuro",
    "minecraft:mangrove_fence": "Valla de Manglar",
    "minecraft:cherry_fence": "Valla de Cerezo",
    "minecraft:bamboo_fence": "Valla de Bambú",
    "minecraft:crimson_fence": "Valla Carmesí",
    "minecraft:warped_fence": "Valla Distorsionada",
    "minecraft:nether_brick_fence": "Valla de Ladrillo del Nether",
    // Puertas de Valla
    "minecraft:oak_fence_gate": "Puerta de Valla de Roble",
    "minecraft:spruce_fence_gate": "Puerta de Valla de Abeto",
    "minecraft:birch_fence_gate": "Puerta de Valla de Abedul",
    "minecraft:jungle_fence_gate": "Puerta de Valla de Jungla",
    "minecraft:acacia_fence_gate": "Puerta de Valla de Acacia",
    "minecraft:dark_oak_fence_gate": "Puerta de Valla de Roble Oscuro",
    "minecraft:mangrove_fence_gate": "Puerta de Valla de Manglar",
    "minecraft:cherry_fence_gate": "Puerta de Valla de Cerezo",
    "minecraft:bamboo_fence_gate": "Puerta de Valla de Bambú",
    "minecraft:crimson_fence_gate": "Puerta de Valla Carmesí",
    "minecraft:warped_fence_gate": "Puerta de Valla Distorsionada",

    // --- 💿 DISCOS DE MÚSICA ---
    "minecraft:music_disc_13": "Disco: 13",
    "minecraft:music_disc_cat": "Disco: Cat",
    "minecraft:music_disc_blocks": "Disco: Blocks",
    "minecraft:music_disc_chirp": "Disco: Chirp",
    "minecraft:music_disc_far": "Disco: Far",
    "minecraft:music_disc_mall": "Disco: Mall",
    "minecraft:music_disc_mellohi": "Disco: Mellohi",
    "minecraft:music_disc_stal": "Disco: Stal",
    "minecraft:music_disc_strad": "Disco: Strad",
    "minecraft:music_disc_ward": "Disco: Ward",
    "minecraft:music_disc_11": "Disco: 11",
    "minecraft:music_disc_wait": "Disco: Wait",
    "minecraft:music_disc_otherside": "Disco: Otherside",
    "minecraft:music_disc_relic": "Disco: Relic",
    "minecraft:music_disc_5": "Disco: 5",
    "minecraft:music_disc_pigstep": "Disco: Pigstep",
    "minecraft:music_disc_precipice": "Disco: Precipice",
    "minecraft:music_disc_creator": "Disco: Creator",
    "minecraft:music_disc_creator_music_box": "Disco: Creator (Caja de Música)",
    
    // --- 🚩 BANNERS Y DISEÑOS ---
    "minecraft:white_banner": "Estandarte Blanco",
    // (Los estandartes de colores funcionan igual que las lanas, añade si quieres)
    "minecraft:flower_banner_pattern": "Diseño de Estandarte: Flor",
    "minecraft:creeper_banner_pattern": "Diseño de Estandarte: Creeper",
    "minecraft:skull_banner_pattern": "Diseño de Estandarte: Calavera",
    "minecraft:mojang_banner_pattern": "Diseño de Estandarte: Mojang",
    "minecraft:globe_banner_pattern": "Diseño de Estandarte: Globo",
    "minecraft:piglin_banner_pattern": "Diseño de Estandarte: Piglin",
    "minecraft:flow_banner_pattern": "Diseño de Estandarte: Flujo",
    "minecraft:guster_banner_pattern": "Diseño de Estandarte: Torbellino",
    
    // --- 🏺 CERÁMICA (Decoración Arqueología) ---
    "minecraft:angler_pottery_sherd": "Fragmento: Pescador",
    "minecraft:archer_pottery_sherd": "Fragmento: Arquero",
    "minecraft:arms_up_pottery_sherd": "Fragmento: Brazos Arriba",
    "minecraft:blade_pottery_sherd": "Fragmento: Cuchilla",
    "minecraft:brewer_pottery_sherd": "Fragmento: Destilador",
    "minecraft:burn_pottery_sherd": "Fragmento: Fuego",
    "minecraft:danger_pottery_sherd": "Fragmento: Peligro",
    "minecraft:explorer_pottery_sherd": "Fragmento: Explorador",
    "minecraft:friend_pottery_sherd": "Fragmento: Amigo",
    "minecraft:heart_pottery_sherd": "Fragmento: Corazón",
    "minecraft:heartbreak_pottery_sherd": "Fragmento: Corazón Roto",
    "minecraft:howl_pottery_sherd": "Fragmento: Aullido",
    "minecraft:miner_pottery_sherd": "Fragmento: Minero",
    "minecraft:mourner_pottery_sherd": "Fragmento: Doliente",
    "minecraft:plenty_pottery_sherd": "Fragmento: Abundancia",
    "minecraft:prize_pottery_sherd": "Fragmento: Premio",
    "minecraft:sheaf_pottery_sherd": "Fragmento: Gavilla",
    "minecraft:shelter_pottery_sherd": "Fragmento: Refugio",
    "minecraft:skull_pottery_sherd": "Fragmento: Calavera",
    "minecraft:snort_pottery_sherd": "Fragmento: Bufido",
    "minecraft:flow_pottery_sherd": "Fragmento: Flujo",
    "minecraft:guster_pottery_sherd": "Fragmento: Torbellino",
    "minecraft:scrape_pottery_sherd": "Fragmento: Rasguño",

    // --- 🧱 HORMIGÓN Y POLVO (Colores) ---
    "minecraft:white_concrete": "Hormigón Blanco",
    "minecraft:orange_concrete": "Hormigón Naranja",
    "minecraft:magenta_concrete": "Hormigón Magenta",
    "minecraft:light_blue_concrete": "Hormigón Azul Claro",
    "minecraft:yellow_concrete": "Hormigón Amarillo",
    "minecraft:lime_concrete": "Hormigón Lima",
    "minecraft:pink_concrete": "Hormigón Rosa",
    "minecraft:gray_concrete": "Hormigón Gris",
    "minecraft:light_gray_concrete": "Hormigón Gris Claro",
    "minecraft:cyan_concrete": "Hormigón Cian",
    "minecraft:purple_concrete": "Hormigón Morado",
    "minecraft:blue_concrete": "Hormigón Azul",
    "minecraft:brown_concrete": "Hormigón Marrón",
    "minecraft:green_concrete": "Hormigón Verde",
    "minecraft:red_concrete": "Hormigón Rojo",
    "minecraft:black_concrete": "Hormigón Negro",
    // Polvo de Hormigón
    "minecraft:white_concrete_powder": "Polvo de Hormigón Blanco",
    "minecraft:black_concrete_powder": "Polvo de Hormigón Negro",
    "minecraft:blue_concrete_powder": "Polvo de Hormigón Azul",
    // (Puedes agregar el resto de colores de polvo si quieres, siguen el mismo patrón)

    // --- 🏺 TERRACOTA (Arcilla Endurecida) ---
    "minecraft:terracotta": "Terracota",
    "minecraft:white_terracotta": "Terracota Blanca",
    "minecraft:orange_terracotta": "Terracota Naranja",
    "minecraft:magenta_terracotta": "Terracota Magenta",
    "minecraft:light_blue_terracotta": "Terracota Azul Claro",
    "minecraft:yellow_terracotta": "Terracota Amarilla",
    "minecraft:lime_terracotta": "Terracota Lima",
    "minecraft:pink_terracotta": "Terracota Rosa",
    "minecraft:gray_terracotta": "Terracota Gris",
    "minecraft:light_gray_terracotta": "Terracota Gris Claro",
    "minecraft:cyan_terracotta": "Terracota Cian",
    "minecraft:purple_terracotta": "Terracota Morada",
    "minecraft:blue_terracotta": "Terracota Azul",
    "minecraft:brown_terracotta": "Terracota Marrón",
    "minecraft:green_terracotta": "Terracota Verde",
    "minecraft:red_terracotta": "Terracota Roja",
    "minecraft:black_terracotta": "Terracota Negra",

    // --- 🪟 PANELES DE CRISTAL ---
    "minecraft:glass_pane": "Panel de Cristal",
    "minecraft:white_stained_glass_pane": "Panel de Cristal Blanco",
    "minecraft:black_stained_glass_pane": "Panel de Cristal Negro",
    "minecraft:gray_stained_glass_pane": "Panel de Cristal Gris",
    // (El resto de colores funcionan igual: color_stained_glass_pane)

    // --- 🚣 BARCOS Y COFRES ---
    "minecraft:oak_boat": "Barco de Roble",
    "minecraft:oak_chest_boat": "Barco con Cofre de Roble",
    "minecraft:spruce_boat": "Barco de Abeto",
    "minecraft:spruce_chest_boat": "Barco con Cofre de Abeto",
    "minecraft:birch_boat": "Barco de Abedul",
    "minecraft:birch_chest_boat": "Barco con Cofre de Abedul",
    "minecraft:jungle_boat": "Barco de Jungla",
    "minecraft:jungle_chest_boat": "Barco con Cofre de Jungla",
    "minecraft:acacia_boat": "Barco de Acacia",
    "minecraft:acacia_chest_boat": "Barco con Cofre de Acacia",
    "minecraft:dark_oak_boat": "Barco de Roble Oscuro",
    "minecraft:dark_oak_chest_boat": "Barco con Cofre de Roble Oscuro",
    "minecraft:mangrove_boat": "Barco de Manglar",
    "minecraft:mangrove_chest_boat": "Barco con Cofre de Manglar",
    "minecraft:cherry_boat": "Barco de Cerezo",
    "minecraft:cherry_chest_boat": "Barco con Cofre de Cerezo",
    "minecraft:bamboo_raft": "Balsa de Bambú",
    "minecraft:bamboo_chest_raft": "Balsa con Cofre de Bambú",

    // --- 📦 CAJAS DE SHULKER (Mochilas) ---
    "minecraft:shulker_box": "Caja de Shulker (Original)",
    "minecraft:white_shulker_box": "Shulker Blanca",
    "minecraft:orange_shulker_box": "Shulker Naranja",
    "minecraft:magenta_shulker_box": "Shulker Magenta",
    "minecraft:light_blue_shulker_box": "Shulker Azul Claro",
    "minecraft:yellow_shulker_box": "Shulker Amarilla",
    "minecraft:lime_shulker_box": "Shulker Lima",
    "minecraft:pink_shulker_box": "Shulker Rosa",
    "minecraft:gray_shulker_box": "Shulker Gris",
    "minecraft:light_gray_shulker_box": "Shulker Gris Claro",
    "minecraft:cyan_shulker_box": "Shulker Cian",
    "minecraft:purple_shulker_box": "Shulker Morada",
    "minecraft:blue_shulker_box": "Shulker Azul",
    "minecraft:brown_shulker_box": "Shulker Marrón",
    "minecraft:green_shulker_box": "Shulker Verde",
    "minecraft:red_shulker_box": "Shulker Roja",
    "minecraft:black_shulker_box": "Shulker Negra",

    // --- 💀 CABEZAS Y VARIOS ---
    "minecraft:skull": "Calavera de Esqueleto",
    "minecraft:wither_skeleton_skull": "Calavera de Wither",
    "minecraft:zombie_head": "Cabeza de Zombi",
    "minecraft:creeper_head": "Cabeza de Creeper",
    "minecraft:piglin_head": "Cabeza de Piglin",
    "minecraft:dragon_head": "Cabeza de Dragón",
    "minecraft:name_tag": "Etiqueta de Nombre",
    "minecraft:saddle": "Montura",
    "minecraft:armor_stand": "Soporte de Armadura",
    "minecraft:end_crystal": "Cristal del End"
    
};

// ... (Aquí termina el DICCIONARIO_ITEMS) ...

export const DICCIONARIO_EFECTOS = {
    "water": "Agua",
    "mundane": "Mundana",
    "thick": "Densa",
    "awkward": "Rara",
    "night_vision": "Visión Nocturna",
    "long_night_vision": "Visión Nocturna +",
    "invisibility": "Invisibilidad",
    "long_invisibility": "Invisibilidad +",
    "leaping": "Salto",
    "long_leaping": "Salto +",
    "strong_leaping": "Salto II",
    "fire_resistance": "Resistencia al Fuego",
    "long_fire_resistance": "Resistencia Fuego +",
    "swiftness": "Rapidez",
    "long_swiftness": "Rapidez +",
    "strong_swiftness": "Rapidez II",
    "slowness": "Lentitud",
    "long_slowness": "Lentitud +",
    "strong_slowness": "Lentitud IV",
    "water_breathing": "Respiración Acuática",
    "long_water_breathing": "Resp. Acuática +",
    "healing": "Curación",
    "strong_healing": "Curación II",
    "harming": "Daño",
    "strong_harming": "Daño II",
    "poison": "Veneno",
    "long_poison": "Veneno +",
    "strong_poison": "Veneno II",
    "regeneration": "Regeneración",
    "long_regeneration": "Regeneración +",
    "strong_regeneration": "Regeneración II",
    "strength": "Fuerza",
    "long_strength": "Fuerza +",
    "strong_strength": "Fuerza II",
    "weakness": "Debilidad",
    "long_weakness": "Debilidad +",
    "decay": "Descomposición (Wither)",
    "turtle_master": "Maestro Tortuga",
    "long_turtle_master": "Maestro Tortuga +",
    "strong_turtle_master": "Maestro Tortuga II",
    "slow_falling": "Caída Lenta",
    "long_slow_falling": "Caída Lenta +"
};